apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-ebs-az-injector
webhooks:
- name: aws-ebs-az-injector.paas
  rules:
  - operations: [ "CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Ignore
  clientConfig:
    service:
      name: webhook-service
      namespace: webhook-namespace
      path: "/inject"
    caBundle: <base64 encoded ca bundle>