name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:
    branches:
      - main  # Change as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ github.actor }}/aws-ebs-az-aware-webhook:${{ github.sha }}
          platforms: linux/amd64,linux/arm64