name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:
    branches:
      - main  # Change as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/aws-ebs-az-aware-webhook:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/aws-ebs-az-aware-webhook:${{ github.sha }}